### ISSUE TITLE
Connector for Phemex API?

### ISSUE THREAD

**Issue by caressgents** [assassinen/grid_bot_client#19]
Any possibility of integrating Phemex exchange API connectors?

**Comment by assassinen** [comment]
What you need to trade on phemex.com ?

**Comment by caressgents** [comment]
BTC/USD contract trading tools. The leveraged trading products.

**Comment by assassinen** [comment]
Do you want THIS ROBOT to work with BTC/USD contract on phemex.com?

**Comment by assassinen** [comment]
https://phemex.com/trade/inverse/BTCUSD - этот инструмент нужен?

**Comment by caressgents** [comment]
Yes exactly that pair I'd need the bot to work with

**Comment by assassinen** [comment]
There are already tasks for the next 2-3 months

**Comment by caressgents** [comment]
Just following up with the Phemex integration. Still in pipeline by chance?

**Comment by caressgents** [comment]
@assassinen any updated here for phemex?

**Comment by assassinen** [comment]
no and not planned any time soon

**Comment by caressgents** [comment]
@assassinen understood. How about ByBit? :)

**Comment by assassinen** [comment]
no and not planned any time soon
